routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FileUploadController;
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth:api']], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('file-upload', FileUploadController::class);
    Route::get('my-conversions', [FileUploadController::class,'index'])->name('my.conversion');
});

Route::post('logout', function () {
    auth()->logout();
    return redirect('/login')->withCookie(\Cookie::forget('passport_token'));
})->name('logout');


Route::get('passport-install', function () {
    Artisan::call('passport:install');
    return 'passport installed';
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Laravel\Passport\HasApiTokens;


class User extends Authenticatable implements HasMedia
{
    use HasApiTokens, HasFactory, Notifiable , InteractsWithMedia;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function conversions()
    {
        return $this->hasMany(UserConversion::class,'user_id','id');
    }
}

app/Models/UserConversion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class UserConversion extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = [
        'user_id',
        'status',
        'filename'
    ];
}

app/Http/Controllers/ApiAuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class ApiAuthController extends Controller
{
    /**
     * Registration
     */
    public function register(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:4',
            'email' => 'required|email',
            'password' => 'required|min:8',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        $token = $user->createToken('Revoke')->accessToken;

        return response()->json(['token' => $token], 200);
    }

    /**
     * Login
     */
    // public function login(Request $request)
    // {
    //     $data = [
    //         'email' => $request->email,
    //         'password' => $request->password
    //     ];

    //     if (Auth::attempt($data)) {
    //         $token = auth()->user()->createToken('Revoke')->accessToken;
    //         setcookie("passport_token", $token);
    //         return response()->json(['token' => $token], 200);
    //     } else {
    //         return response()->json(['error' => 'Unauthorised'], 401);
    //     }
    // }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileUploadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use CloudConvert\Laravel\Facades\CloudConvert;
use CloudConvert\Models\Job;
use CloudConvert\Models\Task;
use Illuminate\Support\Facades\Storage;
use App\Models\UserConversion;

class FileUploadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $conversions = UserConversion::whereUserId(auth()->id())->paginate(5);
        return view('conversion',compact('conversions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = $request->file('file');
        $random = mt_rand(8,15);

        // $file->move(public_path('docs'), $fileName);

        $fileUpload = auth()->user()->conversions()->create([
            'filename'  =>  $random,
            'status'    =>  0
        ]);

        $fileUpload->addMedia($file)->toMediaCollection('files');

        $url = $this->convert($fileUpload);
        return response()->json(['success' => UserConversion::find($fileUpload->id)->getFirstMediaUrl('converted')]);
    }

    public function convert($fileUpload)
    {
        $job = (new Job())
            ->addTask(new Task('import/upload','upload-my-file'))
            ->addTask(
                (new Task('convert', 'convert-my-file'))
                    ->set('input', 'upload-my-file')
                    ->set('output_format', 'pdf')
            )
            ->addTask(
                (new Task('export/url', 'export-my-file'))
                    ->set('input', 'convert-my-file')
            );

        CloudConvert::jobs()->create($job);

        $uploadTask = $job->getTasks()->whereName('upload-my-file')[0];

        $inputStream = fopen($fileUpload->getFirstMedia('files')->getPath(), 'r');

        CloudConvert::tasks()->upload($uploadTask, $inputStream);


        CloudConvert::jobs()->wait($job); // Wait for job completion

        foreach ($job->getExportUrls() as $file) {
            $fileUpload->addMediaFromUrl($file->url)->toMediaCollection('converted');
            $fileUpload->status = 1;
            $fileUpload->save();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/conversion.blade.php
@extends('layouts.app')

@section('css')
@endsection

@section('content')
<div class="container">
    <div class="row pb-2">
        <div class="col-md-8">
            <h4>My Conversions</h4>
        </div>
    </div>

    <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Conversions</li>
    </ol>
    </nav>

    <table id="dtBasicExample" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th class="th-sm">Id
            </th>
            <th class="th-sm">Uploaded File
            </th>
            <th class="th-sm">Converted File
            </th>
          </tr>
        </thead>
        <tbody>
            @foreach ($conversions as $conversion)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td><a href="{{ $conversion->getFirstMediaUrl('files') }}">Download</a></td>
                <td> <a href="{{ $conversion->getFirstMediaUrl('converted') }}">Download</a></td>
            </tr>
            @endforeach
        </tbody>
      </table>
      {{ $conversions->links() }}
</div>
@section('script')
@endsection

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/min/dropzone.min.css">
    <style>
        .alert p{
            margin-bottom: 0rem !important;
        }
    </style>
@endsection

@section('content')
<div class="container">
    <div class="alert alert-danger alert-dismissible" role="alert" style="display: none;">
        <p id="message"></p>
    </div>

    <div class="text-center">
        <h3>Convert Word to PDF</h3><br>
        <p>* Please chose your file or drag and drop which you want to convert.</p>
    </div>

    <div class="text-center">
        <form method="post" action="{{ route('file-upload.store') }}" enctype="multipart/form-data" class="dropzone" id="dropzone">
            @csrf
        </form>
    </div>
    <div class="text-center pt-5 pb-3">
        <h4 >How to convert Word to PDF online:</h4>
    </div>

    <div class="row text-center">

        <div class="col-md-3">
            <img src="{{ asset('img/1.svg') }}" alt="">
            <p>1. To begin, drag and drop your DOC or DOCX file in the Word to PDF converter.</p>
        </div>
        <div class="col-md-3">
            <img src="{{ asset('img/2.svg') }}" alt="">
            <p>2. The conversion to PDF should take place right away.</p>
        </div>
        <div class="col-md-3">
            <img src="{{ asset('img/3.svg') }}" alt="">
            <p>3. Feel free to compress, edit or modify your file further.</p>
        </div>
        <div class="col-md-3">
            <img src="{{ asset('img/4.svg') }}" alt="">
            <p>4. Click the download button to save your new PDF.</p>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="text-center  pt-5" id="loader" style="display: none">
            <img class="" src="{{ asset('img/1486.gif') }}" alt="">
            <h3>Converting...</h3>
        </div>
        <div class="text-center" id="download_section" style="display: none; padding-top: 5em;">
           <h3>Download the converted file from <a href="" id="download" target="_blank">here</a>.</h3>
        </div>
    </div>

</div>

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/dropzone.js"></script>
<!-- Font Awesome JS -->
<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

<script type="text/javascript">
    Dropzone.options.dropzone =
    {
        maxFilesize: 12,
        resizeQuality: 1.0,
        acceptedFiles: ".doc,.docx",
        addRemoveLinks: true,
        timeout: 60000,
        processing: function()
        {
            $('.alert').hide();
            $('#loader').show()
            $('html, body').animate({
                scrollTop: $("#loader").offset().top
            }, 2000);
        },
        removedfile: function(file)
        {
            $('.alert').hide();
            $('#download_section').hide()
            var fileRef;
            return (fileRef = file.previewElement) != null ?
            fileRef.parentNode.removeChild(file.previewElement) : void 0;

        },
        success: function (file, response) {
            console.log(response);
            $('#loader').hide()
            $('#download_section').show()
            $('#download').attr('href',response.success)
        },
        error: function (file, response) {
            if(response.message) {
                $('.alert').show();
                $('#message').text(response.message);
                $('html, body').animate({
                    scrollTop: $("#app").offset().top
                }, 2000);
                $('#loader').hide();
                $('#download_section').hide()
            }
        }
    };

</script>

@endsection
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Doc2PDF</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @yield('css')
</head>

<body>
    <div id="app">
        @include('partials.header')
        <main class="py-4">
            @yield('content')
        </main>

        <div class="container pt-5">
            @include('partials.footer')
        </div>

    </div>
    @yield('script')
</body>

</html>

resources/views/partials/footer.blade.php
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <h3>Doc2PDF</h3>
            <small class="d-block mb-3 text-muted">© 2021-2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>

resources/views/partials/header.blade.php
<nav class="navbar navbar-expand-md navbar-light shadow-sm" style="background-color: #49c8f2 !important">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}" style="font-size: 1.575rem;">
            Doc2PDF
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>


                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('my.conversion') }}">
                                My Conversions
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>


                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>